/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const collection = new Collection({
      createRule: null,
      deleteRule: null,
      fields: [
        {
          autogeneratePattern: "[a-z0-9]{15}",
          help: "",
          hidden: false,
          id: "text3208210256",
          max: 15,
          min: 15,
          name: "id",
          pattern: "^[a-z0-9]+$",
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: "text",
        },
        {
          autogeneratePattern: "",
          help: "",
          hidden: false,
          id: "text1699441889",
          max: 0,
          min: 0,
          name: "targetCollectionName",
          pattern: "",
          presentable: true,
          primaryKey: false,
          required: true,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          help: "",
          hidden: false,
          id: "text3689461544",
          max: 0,
          min: 0,
          name: "toolNameOverride",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          help: "",
          hidden: false,
          id: "text1704208859",
          max: 0,
          min: 0,
          name: "icon",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          help: "",
          hidden: false,
          id: "text3168856643",
          max: 0,
          min: 0,
          name: "accentColour",
          pattern: "^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$",
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: "text",
        },
        {
          help: "",
          hidden: false,
          id: "select976907234",
          maxSelect: 0,
          name: "layout",
          presentable: false,
          required: true,
          system: false,
          type: "select",
          values: ["detail", "list", "gallery", "table"],
        },
        {
          hidden: false,
          id: "autodate2990389176",
          name: "created",
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: "autodate",
        },
        {
          hidden: false,
          id: "autodate3332085495",
          name: "updated",
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: "autodate",
        },
      ],
      indexes: [
        "CREATE UNIQUE INDEX idx_tools_target_collection_name ON _tools (targetCollectionName)",
      ],
      id: "pbc_565993628",
      listRule: null,
      name: "_tools",
      system: true,
      type: "base",
      updateRule: null,
      viewRule: null,
    });

    return app.save(collection);
  },
  (app) => {
    const collection = app.findCollectionByNameOrId("pbc_565993628");

    return app.delete(collection);
  },
);
